name: 🧠 Update LeetCode Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate LeetCode stats card
        uses: realpenguin7/leetcode-stats-card@main
        with:
          username: jamie10x
          theme: dark  # or "light", "unicorn", "ocean", etc.
          markdown_file: README.md
