name: 🧠 Update LeetCode Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update LeetCode Card in README
        run: |
          echo "## 📊 LeetCode Stats" > README.md
          echo "" >> README.md
          echo "![LeetCode Stats](https://leetcard.jacoblin.cool/jamie10x?theme=dark&ext=contest)" >> README.md
