name: 🧠 Update LeetCode Stats

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Inject LeetCode card into README
        run: |
          awk '/<!--LEETCODE-START-->/ { print; print "![LeetCode Stats](https://leetcard.jacoblin.cool/jamie10x?theme=dark&ext=contest)"; in_block=1; next }
               /<!--LEETCODE-END-->/ { in_block=0 }
               !in_block' README.md > temp && mv temp README.md

      - name: Commit and push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add README.md
          git commit -m "Update LeetCode stats card" || echo "No changes to commit"
          git push
